---
name: WWW-FMyLife
version: 0.08
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'Tamir Lousky <tlousky@cpan.org>'
abstract: Obtain FMyLife.com anecdotes via API
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/xsawyerx/www-fmylife/tree/master
build_requires:
  Net::Ping: 0
  Test::Deep: 0
  Test::MockObject::Extends: 0
  Test::More: 0.88
requires:
  LWP::UserAgent: 0
  Moose: 0.86
  XML::Simple: 2.18
configure_requires:
  Module::Build: 0.35
provides:
  WWW::FMyLife:
    file: lib/WWW/FMyLife.pm
    version: 0.08
  WWW::FMyLife::Comment:
    file: lib/WWW/FMyLife/Comment.pm
    version: 0.02
  WWW::FMyLife::Item:
    file: lib/WWW/FMyLife/Item.pm
    version: 0.04
  WWW::FMyLife::Vote:
    file: lib/WWW/FMyLife/Vote.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - fml
  - fmylife
